# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #turn on dns resolution for ubuntu ?maybe
  config.vm.provider "virtualbox" do |v| 
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # create ansib node
  config.vm.define :ansib do |ansib_config|
      ansib_config.vm.box = "ubuntu/trusty64"
      ansib_config.vm.hostname = "ansib"
      ansib_config.vm.network :private_network, ip: "10.0.15.40"
      ansib_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
      ansib_config.vm.provision :shell, path: "bootstrap-ansib.sh"
  end

#  # create load balancer
#  config.vm.define :lb do |lb_config|
#      lb_config.vm.box = "ubuntu/trusty64"
#      lb_config.vm.hostname = "lb"
#      lb_config.vm.network :private_network, ip: "10.0.15.11"
#      lb_config.vm.network "forwarded_port", guest: 80, host: 8080
#      lb_config.vm.provider "virtualbox" do |vb|
#        vb.memory = "256"
#      end
#  end

  ## create some web servers
  ## https://docs.vagrantup.com/v2/vagrantfile/tips.html
  #(1..2).each do |i|
  #  config.vm.define "web#{i}" do |node|
  #      node.vm.box = "ubuntu/trusty64"
  #      node.vm.hostname = "web#{i}"
  #      node.vm.network :private_network, ip: "10.0.15.2#{i}"
  #      node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
  #      node.vm.provider "virtualbox" do |vb|
  #        vb.memory = "256"
  #      end
  #  end
  #end

end
