---
- name: Install AWS CLI
  hosts: all
  user: ubuntu
  sudo: yes
#  become: yes
#  become_user: root
#  become_method: sudo
  tasks:
   - name: Install PIP
     apt: pkg=python-pip state=latest update_cache=yes

   - name: Install boto
     pip: name=boto state=latest

   - name: Install AWS CLI interface
     pip: name=awscli state=latest


